version: '3'
services:
  nginx:
    build: nginx
    container_name: nginx
    ports:
      - "8080:80"
    restart: always

  app:
    build: app
    container_name: app
    expose:
      - "8080"

  db:
    image: "mysql:5.7"
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpwd
