version: '3'

services:

  nginx:
    build: nginx
    container_name: proxy
    ports:
      - "8080:80"
    networks: 
      - challenge

  app:
    build: app
    container_name: app
    expose:
      - "8080"
    networks: 
      - challenge

  db:
    image: "mysql:5.7"
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpwd
    networks: 
      - challenge

networks:
  challenge:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"